In [1]:
from mesh_dataset_utils import *
from mesh_experiment import Experiment
from MLP import MLP
import torch
from torch import nn
from sklearn.model_selection import train_test_split
from datetime import datetime

In [2]:
DATASET_NAME = 'spikey_1_partial_smooth'

In [3]:
dataset = np.load(f'npz_train/{DATASET_NAME}.npz')

In [4]:
X = dataset['fourier']
y = dataset['target']

In [5]:
X.shape

(42787, 100)

In [6]:
y.shape

(42787, 3)

In [7]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15, random_state=11)

In [8]:
batch_size = 1000
train_data = torch.utils.data.TensorDataset(torch.tensor(X_train).float(), torch.tensor(y_train).float())
train_loader = torch.utils.data.DataLoader(train_data, batch_size=batch_size, shuffle=True)

test_data = torch.utils.data.TensorDataset(torch.tensor(X_test).float(), torch.tensor(y_test).float())
test_loader = torch.utils.data.DataLoader(test_data, batch_size=batch_size, shuffle=True)

In [9]:
model = MLP(
            input_dim=X.shape[1],
            output_dim=y.shape[1],
            hidden_dim=512,
            n_layers=6,
            geometric_init=True,
            beta=True,
            sine=True,
            all_sine=True,
            skip=True,
            bn=True,
            dropout=0.0
            )

In [10]:
lr=1e-4
optimizer = torch.optim.Adam(model.parameters(), lr=lr)
loss_fn = nn.MSELoss()
epochs = 6
rand_inits = 2
now = datetime.now()

OUT_DIR = f'experiments/{now.strftime("%m_%d_%y_%H:%M:%S")}_{DATASET_NAME}'
model_info = {'test': 'TEST!!'}

In [11]:
OUT_DIR

'experiments/04_14_23_09:15:34_spikey_1_partial_smooth'

In [12]:
exp = Experiment(model,
                    optimizer,
                    loss_fn,
                    train_loader,
                    test_loader,
                    epochs,
                    rand_inits,
                    OUT_DIR,
                    model_info,
                    rand_seed=11)

In [13]:
log = exp.run()

started training for 6 epochs
epoch 0 training loss: 0.862726675497519 eval loss: 0.7290018796920776
epoch 5 training loss: 0.11625583751781567 eval loss: 0.07707235962152481
started training for 6 epochs
epoch 0 training loss: 0.06942808305895007 eval loss: 0.03242572396993637
epoch 5 training loss: 0.003752004455875706 eval loss: 0.006446818821132183


In [14]:
log

{'model': 'MLP(\n  (model): ModuleList(\n    (0): Linear(in_features=100, out_features=512, bias=True)\n    (1): Sine()\n    (2): LayerNorm((512,), eps=1e-05, elementwise_affine=True)\n    (3): Linear(in_features=512, out_features=512, bias=True)\n    (4): Sine()\n    (5): LayerNorm((512,), eps=1e-05, elementwise_affine=True)\n    (6): Linear(in_features=512, out_features=512, bias=True)\n    (7): Sine()\n    (8): LayerNorm((512,), eps=1e-05, elementwise_affine=True)\n    (9): Linear(in_features=612, out_features=512, bias=True)\n    (10): Sine()\n    (11): LayerNorm((512,), eps=1e-05, elementwise_affine=True)\n    (12): Linear(in_features=512, out_features=512, bias=True)\n    (13): Sine()\n    (14): LayerNorm((512,), eps=1e-05, elementwise_affine=True)\n    (15): Linear(in_features=512, out_features=3, bias=True)\n  )\n)',
 'optimizer': 'Adam (\nParameter Group 0\n    amsgrad: False\n    betas: (0.9, 0.999)\n    capturable: False\n    eps: 1e-08\n    foreach: None\n    lr: 0.0001\n  

In [32]:
import numpy as np

# Example input vector x
x = np.array([1, 2, 3])

# Example output vector y
y = np.array([4, 5, 6])

# Create matrices X and Y from input and output vectors
X = np.vstack([x])
Y = np.vstack([y])

# Find the linear transformation matrix A using least squares regression
A, residuals, rank, s = np.linalg.lstsq(X, Y, rcond=None)

# Print the linear transformation matrix A
print("Linear Transformation Matrix A:")
print(A)

Linear Transformation Matrix A:
[[0.28571429 0.35714286 0.42857143]
 [0.57142857 0.71428571 0.85714286]
 [0.85714286 1.07142857 1.28571429]]


In [34]:
x.dot(A)

array([4., 5., 6.])

In [11]:
a = np.array([7,23,156,67,5,4])
b = np.array([71,35,12,1,0,50])

In [12]:
A = get_linear_transformation(a, b)

In [13]:
A.shape

(6, 6)

In [14]:
a.dot(A)

array([71., 35., 12.,  1.,  0., 50.])