In [14]:
from mesh_dataset_utils import *
from mesh_experiment import Experiment
from MLP import MLP
import torch
from torch import nn
from sklearn.model_selection import train_test_split

In [3]:
DIRECTORY_NAME = 'spikey_1_partial_smooth'

In [4]:
dataset = np.load(f'npz_train/{DIRECTORY_NAME}.npz')

In [5]:
X = dataset['fourier']
y = dataset['target']

In [6]:
X.shape

(42787, 100)

In [7]:
y.shape

(42787, 3)

In [26]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.15, random_state=11)

In [27]:
batch_size = 1000
train_data = torch.utils.data.TensorDataset(torch.tensor(X_train).float(), torch.tensor(y_train).float())
train_loader = torch.utils.data.DataLoader(train_data, batch_size=batch_size, shuffle=True)

test_data = torch.utils.data.TensorDataset(torch.tensor(X_test).float(), torch.tensor(y_test).float())
test_loader = torch.utils.data.DataLoader(test_data, batch_size=batch_size, shuffle=True)

In [28]:
model = MLP(
            input_dim=X.shape[1],
            output_dim=y.shape[1],
            hidden_dim=512,
            n_layers=6,
            geometric_init=True,
            beta=True,
            sine=True,
            all_sine=True,
            skip=True,
            bn=True,
            dropout=0.0
            )

In [29]:
lr=1e-4
optimizer = torch.optim.Adam(model.parameters(), lr=lr)
loss_fn = nn.MSELoss()
epochs = 20
rand_inits = 2
OUT_DIR = 'experiments'
model_info = {'test': 'TEST!!'}

In [30]:
exp = Experiment(model,
                    optimizer,
                    loss_fn,
                    train_loader,
                    test_loader,
                    epochs,
                    rand_inits,
                    OUT_DIR,
                    model_info,
                    rand_seed=11)

In [31]:
log = exp.run()

started training for 20 epochs
epoch 0 training loss: 0.8636501930855416 eval loss: 0.7156544327735901
epoch 5 training loss: 0.11824432579246727 eval loss: 0.09782876074314117
epoch 10 training loss: 0.0072446457437566805 eval loss: 0.0024675647728145123
epoch 15 training loss: 0.0019163898116833454 eval loss: 0.0015994010027498007
started training for 20 epochs
epoch 0 training loss: 0.001335379944459812 eval loss: 0.000758034351747483
epoch 5 training loss: 0.0013682750632634034 eval loss: 0.0009409158956259489
epoch 10 training loss: 0.0010978406345522082 eval loss: 0.00070137158036232
epoch 15 training loss: 0.0010127148314102276 eval loss: 0.0015137071022763848


ValueError: dictionary update sequence element #0 has length 4; 2 is required

In [32]:
import numpy as np

# Example input vector x
x = np.array([1, 2, 3])

# Example output vector y
y = np.array([4, 5, 6])

# Create matrices X and Y from input and output vectors
X = np.vstack([x])
Y = np.vstack([y])

# Find the linear transformation matrix A using least squares regression
A, residuals, rank, s = np.linalg.lstsq(X, Y, rcond=None)

# Print the linear transformation matrix A
print("Linear Transformation Matrix A:")
print(A)

Linear Transformation Matrix A:
[[0.28571429 0.35714286 0.42857143]
 [0.57142857 0.71428571 0.85714286]
 [0.85714286 1.07142857 1.28571429]]


In [34]:
x.dot(A)

array([4., 5., 6.])

In [36]:
def get_linear_transformation(x1, x2):
    X1 = np.vstack([x1])
    X2 = np.vstack([x2])
    
    A, residuals, rank, s = np.linalg.lstsq(X, Y, rcond=None)
    
    return A
    